### ISSUE TITLE
Polishing

### ISSUE THREAD

**Issue by 11jo** [The-Gate-Project/Volcano_Pack#1]
Hello, @ALIENQuake !

I made a mistake with [volcano.ini](https://github.com/Black-Wyrm-Lair/Volcano_Pack/blob/update-1/volcano/volcano.ini)

Download = https://github.com/The-Gate-Project/Volcano_Pack/releases

Should be without the "release" part I think, and sorry I am not used yet to the kind of polishing you're doing right now.

Download = https://github.com/Black-Wyrm-Lair/Volcano_Pack

**Comment by ALIENQuake** [comment]
@11jo Hey, 
no problem, I've already spotted it and prepared a minor update #2 
BTW: After you transfer the repos, you can still perform code updates 😃
